locations_name = {
"babson_hall":"Babson Hall",
"babson_lot":"Babson Lot",
"becc":"Babson Executive Conference Center",
"becc_lot":"BECC Garage",
"blank":"Arthur M. Blank Center",
"brac":"Babson Recreation and Athletics Complex",
"bryant":"Bryant Hall",
"bryant_lot":"Bryant Lot",
"bsc":"Boston Sports Club",
"canfield":"Canfield Hall",
"central_services":"Central Services",
"chapel":"Glavin Family Chapel",
"coleman":"Coleman Hall",
"coleman_lot":"Coleman Lot",
"commons":"Babson Commons",
"cruikshank":"William Cruickshank Alumni Hall",
"forest":"Forest Hall",
"forest_annex":"Forest Hall (Annex)",
"forest_lot":"Forest Lot",
"foundry":"the Weissman Foundry",
"foundry_lot":"Foundry Lot",
"gerber":"Gerber Hall",
"globe":"the Globe",
"hartwell_rogers_field":"Hartwell Rogers Field",
"hollister":"Hollister Hall",
"hollister_lot":"Hollister Lot",
"horn":"Horn Library",
"horn_cpu":"Horn Library Computer Center",
"innovation":"the Innovation Center",
"isbrandtsen_field":"Isbrandtsen Field",
"keith":"Keith Hall",
"knight":"Knight Auditorium",
"knight_lot":"Knight Lot",
"kriebel":"Kriebel Hall",
"luksic":"Luksic Hall",
"macdowell_field":"MacDowell Field",
"malloy":"Malloy Hall",
"mandell":"Mandell Family Hall",
"manor_central":"Park Manor Central",
"manor_north":"Park Manor North",
"manor_quad":"Park Manor Quad",
"manor_south":"Park Manor South",
"manor_west":"Park Manor West",
"mattos":"Mattos Hall",
"mccullough":"McCullough Hall",
"millea":"Millea Hall",
"mustard":"Mustard Hall- Admissions",
"nichols":"Nichols Building",
"nichols_lot":"Nichols Lot",
"olin":"Olin Hall",
"olin_lot":"Olin Lot",
"path_babson_way_1":"Babson Way",
"path_babson_way_2":"Babson Way",
"path_babson_way_3":"Babson Way",
"path_bryant_way":"Bryant Way",
"path_college_1":"Babson College Drive",
"path_college_2":"Babson College Drive",
"path_college_3":"Babson College Drive",
"path_college_4":"Babson College Drive",
"path_college_5":"Babson College Drive",
"path_college_6":"Babson College Drive",
"path_college_7":"Babson College Drive",
"path_college_8":"Babson College Drive",
"path_fields_bryant":"the path from the fields to Bryant Way",
"path_fields_seating":"fields' spectator seating",
"path_fields_side":"the path behind the softball field",
"path_keith_canfield":"the path between Kieth Hall and Canfield Hall",
"path_manor_way_1":"Park Manor Way",
"path_manor_way_2":"Park Manor Way",
"path_manor_way_3":"Park Manor Way",
"path_map_hill_1":"Map Hill Drive",
"path_map_hill_2":"Map Hill Drive",
"path_map_hill_3":"Map Hill Drive",
"path_map_hill_4":"Map Hill Drive",
"path_mustard_blank":"the path between the Blank Center and Mustard Hall",
"path_nichols_1":"Nichols Road",
"path_nichols_2":"Nichols Road",
"path_olin_knight":"the path between Olin Hall and Knight Auditorium",
"path_pietz_mccullough":"the path between Pietz Hall and McCullough Hall",
"path_reynolds_canfield":"the path between Reynolds Center and Canfield Hall",
"path_sullivan":"Sullivan Road",
"path_tomasso_lawn":"the Tomasso lawn",
"path_vw_hill_bottom":"the bottom of Van Winkle Hill",
"path_vw_hill_top":"the top of Van Winkle Hill",
"path_webster_stairs":"the stairs outside the Webster Center",
"pietz":"Pietz Hall",
"post_office":"Post Office - USPS",
"public_safety":"Public Safety",
"putney":"Putney Hall",
"reynolds":"Reynolds Campus Center",
"rogers":"Rogers Pub",
"skating_lot":"Skating Lot",
"skating_rink":"Skating Center",
"softball_field":"Alumni Softball Field",
"sorenson":"Sorenson Center",
"sullivan":"Sullivan Building",
"sullivan_lot":"Sullivan Lot",
"tennis_court":"Tennis Courts",
"tomasso":"Tomasso Hall",
"trim":"Trim Dining Hall",
"trim_lot":"Trim Lot",
"van_winkle":"Van Winkle Hall",
"webster":"Webster Center",
"webster_lot":"Webster Lot",
"westgate":"Westage Hall",
"woodland_1":"Woodland Building 1",
"woodland_10":"Woodland Building 10",
"woodland_2":"Woodland Building 2",
"woodland_2a":"Woodland Building 2A",
"woodland_3":"Woodland Building 3",
"woodland_4":"Woodland Building 4",
"woodland_5":"Woodland Building 5",
"woodland_6":"Woodland Building 6",
"woodland_7":"Woodland Building 7",
"woodland_8":"Woodland Building 8",
"woodland_9":"Woodland Building 9",
"woodland_lot":"Woodland Lot",
"woodside":"Woodside Hall",
"woodside_lot":"Woodland Lot"
}

def locations():
    location_name = []
    for location in locations_name:
        if locations_name[location] not in location_name:
            location_name.append(locations_name[location])
    return sorted(location_name)

def main():
    print(locations())

if __name__ == '__main__':
    main()